# .github/workflows/test01.yaml
name: test workflow quotes page
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium pytest
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Run the PytTest script
        run: pytest -rA
      - name: TestRail CLI upload results
        if: always()
        run: |
          pip install trcli
          trcli -y \
            -h https://dangoss.testrail.io/ \
            --project "Python Test Project" \
            -u dan@dgosselin.com \
            -p T3str4il! \
            parse_junit \
            --title "Automated Tests from GitHub workflow" \
            --run-description ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -f "junit-report.xml"
