name: Testrail-Integration

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - uses: actions/cache@v3
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip freeze > requirements.txt
        - name: Run Test
          run: python -m robot --outputdir results testcases/functional_tests
        - name: Run Test and create report
          run: python -m robot -d reports -x junit-report.xml "testcases/functional_tests"
        - name: Run Robot Framework tests and generate report
          run: |
             echo "ROBOT_RC=$?" >> "$GITHUB_ENV" 
        - name: Publish test results
          uses: actions/upload-artifact@v4
          with:
            name: robot-test-results
            path: results
        - name: Setup Python
          if: always()
          uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - name: Execute TestRail CLI to upload results
          if: always()
          run: |
            pip install trcli 
            trcli -y \
              -h "https://dangoss.testrail.io" \
              --project "Python Test Prroject" \
              --username "dan@dgosselin.com" \
              --password "T3str4il!" \
              parse_junit \
              --title "Robot Framework Automated Tests" \
              -f "reports/junit-report.xml"\
